### ISSUE TITLE
2. UI 정하기 (Xcode를 이용한 프로토 타입 설계)

### ISSUE THREAD

**Issue by dlaghks93** [ProjectInTheClass/WTS#2]

**Comment by dlaghks93** [comment]
살리고 싶은 부분에 대해 글 적습니다!
메인 : 강사님이 말해주신 것처럼 전체 배경으로 여러 분위기를 물어보고 클릭하면 그 분위기에 해당하는 향수 리스트를 보여줌
검색 : 사용자가 미리 향수 이름등을 알고 사용할때 그 향수 정보를 단순하게 보여줌
찜한목록 : 자신이 찜한 향수들의 목록을 보여주면서 만약 찜한 향수 둘중 하나를 고민중일때 비교표?와 같은 형식으로 두 비교대상의 차이점을 보여줌
해시태그는 제품 목록쪽에 & 찜한목록쪽에도 들어가면 비교가 훨씬 쉽고 좋겠네요

**Comment by dlaghks93** [comment]
검색 탭 부분에서 카테고리를 어떻게 이쁘게 넣을수 있을지도 고민해보는게 좋겠네요!
내일 '메인화면 살리는 방안'에 대해 각자 생각해옵시다!

**Comment by YooSunKyeung** [comment]
향에 기반한 분위기를 나누어서 분위기별로 향수를 분류화해서 보여주기.
가장 주된 테마가 '분위기'니까 굳이 다른 카테고리를 만들 필요는 없는 것 같음.
향수들을 메인 향에 따라 어떻게 분위기를 나눠볼지가 관건

**Comment by YooSunKyeung** [comment]
https://pttrns.com/?scid=33 
ui 디자인 참고하기 좋은 것 같아서 올립니다

**Comment by YooSunKyeung** [comment]
https://www.motionelements.com/search?s=cotton&mt=14&subscription=1
gif 이미지 사이트

**Comment by YooSunKyeung** [comment]
https://pixabay.com/ko/videos/비-물-창-젖은-할인되었습니다-피가-뚝뚝-비오는-날-밤-11722/
gif (비디오) 사이트
